### ISSUE TITLE
[Symptom Report] Remove temperature step 

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#180]
Now that temperature is included alongside the other questions, the custom temperature step is superfluous.

**Comment by gspencergoog** [comment]
Ahh, so was the "How high did your temperature get today?" question meant to replace that?

I kept it in because I thought the difference was that the temperature page was asking "what is your temperature right now?" as opposed to the one in the question flow, which was asking about a daily maximum.

**Comment by ferndot** [comment]
@gspencergoog yeah, that replaced it. Thanks for clarifying (I forgot to put its removal in the first issue).
