### ISSUE TITLE
[BUG] Take your temperature screen has overlapping UI elements

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#24]
After scrolling down:
![Screenshot_20200322-143737](https://user-images.githubusercontent.com/551196/77261307-d5e29f00-6c4a-11ea-974f-01f6e1e6e463.png)

**Comment by bkonyi** [comment]
Hm, this doesn't seem to happen consistently. Anyway, I think something needs to be changed in the [ScrollableBody](https://github.com/coronavirus-diary/coronavirus-diary/blob/develop/lib/src/ui/widgets/scrollable_body.dart) widget to resolve this.

**Comment by DarshanGowda0** [comment]
It does happen consistently. Try scrolling it with a horizontal landscape.

**Comment by gspencergoog** [comment]
So, it appears that it is no longer overflowing, but it's still not an ideal experience, since everything is overlapping.

I think that the step counter and the "submit" button should not be pinned to the bottom of the screen, perhaps, but perhaps a UI designer should look at it.  Maybe those pieces of information can go into the App Bar?

![image](https://user-images.githubusercontent.com/8867023/77364112-23294400-6d11-11ea-9cae-3e11dca097da.png)

**Comment by philippecao** [comment]
I don't think the Submit button should be pinned to the bottom of the screen, either. 

Because the keyboard obfuscates the rest of the screen, users won't know whether there's other content they need to see before Submitting. Therefore keeping it pinned doesn't make a ton of sense. 

I think it would stay fixed and the user would either tap out of the keyboard area or tap the Done (green checkmark) key to complete their input.

**Comment by gspencergoog** [comment]
OK, I'll move the step counter and the submit button to scroll with the content.

**Comment by gspencergoog** [comment]
@philippecao This will also mean that the "continue" button on the previous page would also not be pinned, and will scroll with the content, right? There's no text field on the page (yet), but it can still mean that people will miss the last slider and not enter the data.

![image](https://user-images.githubusercontent.com/8867023/77365554-916f0600-6d13-11ea-93cd-4b411f2d7bc5.png)

**Comment by philippecao** [comment]
Ah, I didn't realize that they were tied together ... No, I'm not sure it makes sense for the Continue to be persistent either. 

If we want the user to input all the information before continuing onwards, having it persistent suggests that they can go forward at any point. Really the continue button should be the last step of the flow after filling out all the information.

**Comment by gspencergoog** [comment]
I agree.  I'll use your mocks (I just saw you posted some in the chat).
